GF-13-17-React Dom and Project page
iamdavidpetric/raise-me-client pull request #3
Opened 2022-06-28 08:39 UTC by iamdavidpetric

2022-06-28 08:46 UTC, iamalextodoran requested changes
Define consts just like you would fetch your data from the backend, use objects, arrays etc.

2022-06-28 08:46 UTC, iamalextodoran commented on src/show/Application.js
> +import { BrowserRouter, Routes, Route } from 'react-router-dom';
Group by external libraries first then by in-house made stuff.

2022-06-28 08:46 UTC, iamalextodoran commented on src/show/Application.js
> +      </div>
Why do you need to wrap those into a div?

2022-06-28 08:46 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +import { AiOutlineLink } from 'react-icons/ai';
GROUP AND SORT

2022-06-28 08:46 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +              {[...Array(40)].map(item => (
Define a const (e.g. const projectPictures or const pictures) and use it.

2022-06-28 08:46 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +              src='https://upload.wikimedia.org/wikipedia/commons/d/d8/Elon_Musk_Royal_Society_%28cropped%29.jpg'
Define in a const

2022-06-28 08:46 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +              alt='Elon Musk'
Define in a const

2022-06-28 08:46 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +          Hatz Musk "change your lifestyle with this product or another bs"
Define in a const

2022-06-28 08:46 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +              src='https://i.imgur.com/kHgmAGw.jpg'
Define in a const

2022-06-28 08:46 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +              alt='bacpack'
Define in a const

2022-06-28 08:46 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +              All Access | Outdoor Leisure Backpack
Define in a const

2022-06-28 08:46 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +              which shipping will begin right away.'
Define in a const

2022-06-28 08:46 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +              25.000$/100.000$
Define in a const

2022-06-28 18:18 UTC, iamalextodoran requested changes

2022-06-28 18:18 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +const project_details = {
camel case for this

2022-06-28 18:18 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +  team_members: ['Mihai', 'Petru', 'Alecs', 'Avram'],
this should be an array of objects.

2022-06-28 18:18 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +              {project_details.images.map(item => (
You are already showing the first project picture above, don't do it here too.

2022-06-28 18:22 UTC, iamalextodoran commented
GF-13-17-React Dom and Project page --> GF-13, GF-17 - React Route Dom and Project page

2022-06-29 08:34 UTC, MIKALAKE approved these changes

2022-06-29 11:43 UTC, MIKALAKE commented on package.json
> +    "axios": "^0.27.2",
`^` We want to update versions

2022-06-29 12:50 UTC, iamalextodoran requested changes
Modify the PR title.

And as we spoke, put the first team member, the CEO in one line and a variable, and the rest of the team in the next line (in the UI) and in a different variable.

2022-06-29 12:50 UTC, iamalextodoran commented on package.json
> +    "axios": "^0.27.2",
It's not even supposed to go on this PR.

2022-06-29 12:50 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +              src={projectDetails.team_members[0].avatar_url}
Put the first team member into a variable, and do the same with the rest of the team members.

2022-06-29 12:50 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +              {projectDetails.images.map(item => (
Show all the images, but the first. And put them into a variable

2022-06-29 12:50 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +              src={projectDetails.images[0]}
Put this into a variable

2022-06-29 12:50 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +                      {projectDetails.team_members.slice(2, 3).map()}
Put this in a variable.

2022-06-29 12:50 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +                        {projectDetails.team_members.slice(1, 2).map(member => (
Put this in a variable.

2022-06-29 12:50 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +                        .map(member => member.name)}
Put this in a variable.

2022-06-29 15:35 UTC, iamalextodoran requested changes

2022-06-29 15:35 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +                variant='invertoutline'
Your new variant type is `invert-outline`, use it wisely.

2022-06-29 15:35 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +                      <div className='flex flex-col items-center'>
Your are mapping through an array of members yet I cannot see a key prop so React knows what to re-render.

2022-06-29 15:35 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +              src={projectDetails.images[1]}
Why only show the second image in this array?

2022-06-29 15:35 UTC, iamalextodoran commented on src/show/pages/public/Project/index.js
> +              alt='bacpack'
Typo.

2022-06-29 16:21 UTC, iamalextodoran approved these changes

2022-06-29 16:23 UTC, merged